FROM python:2.7.10
MAINTAINER Giovanni Quattrocchi
RUN  git clone https://github.com/MarconiQuattrocchi/scep2015.git /usr/src/scep2015
WORKDIR /usr/src/scep2015/client
CMD ["python", "/usr/src/scep2015/client/client.py"]
